apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  configManagementPlugins: |-
    - name: kustomize-envvar
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build --enable-helm . | perl -pe 's{\\$(\\{)?(\\w+)(?(1)\\})}{$ENV{$2} // $&}ge'"]
  rbac:
    defaultPolicy: role:readonly
    policy: |
      g, cluster-admins, role:admin
    scopes: '[groups]'
  resourceTrackingMethod: annotation
  server:
    insecure: true
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  sso:
    dex:
      openShiftOAuth: true
    provider: dex
  repo:
    env:
      - name: APP_ENV
        value: prod